import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useState } from "react";

interface LayoutProps {
  children?: React.ReactNode;
}
export default function Sidebar(props: LayoutProps) {
  const [collapse, setCollapse] = useState("collapse");
  const [roomlist, setRoomlist] = useState<string[]>([]);

  useEffect(() => {
    fetch("/api/getRoomlist", {
      method: "POST",
    })
      .then((res) => res.json())
      .then((json) => {
        setRoomlist(json);
      });
  }, []);
  return (
    <div>
      <Head>
        <title>SmartBuilding</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link
          href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
          rel="stylesheet"
        />
      </Head>
      <div id="wrapper">
        <ul
          className="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion"
          id="accordionSidebar"
        >
          <a
            className="sidebar-brand d-flex align-items-center justify-content-center"
            href="/"
          >
            <div className="sidebar-brand-icon rotate-n-15">
              <i className="fas fa-laugh-wink"></i>
            </div>
            <div className="sidebar-brand-text mx-3">SmartBuilding</div>
          </a>

          <hr className="sidebar-divider my-0" />

          <li className="nav-item active">
            <a className="nav-link" href="/dashboard">
              <i className="fas fa-fw fa-tachometer-alt"></i>
              <span>Dashboard</span>
            </a>
            <a className="nav-link" href="/roomcard">
              <i className="fas fa-fw fa-tachometer-alt"></i>
              <span>Roomcard(index 예정)</span>
            </a>
          </li>
          <hr className="sidebar-divider" />

          <div className="sidebar-heading">Interface</div>

          <li className="nav-item">
            <a
              className="nav-link collapsed"
              href="#"
              onClick={() => {
                if ("collapse" === collapse) setCollapse("");
                else setCollapse("collapse");
              }}
            >
              <i className="fas fa-fw fa-cog"></i>
              <span>방 상태 확인</span>
            </a>
            <div
              id="collapseTwo"
              className={collapse}
              aria-labelledby="headingTwo"
              data-parent="#accordionSidebar"
            >
              <div className="bg-white py-2 collapse-inner rounded">
                <h6 className="collapse-header">방 목록:</h6>
                {roomlist.map((room) => {
                  return (
                    <div key={room} className="collapse-item ">
                      <Link
                        className="collapse-item"
                        href={`/Roomlist/${room}`}
                      >
                        {room}
                      </Link>
                    </div>
                  );
                })}
              </div>
            </div>
          </li>
        </ul>
        {props.children}
      </div>
    </div>
  );
}
